#!/usr/bin/env bash

set -euo pipefail

# Configuration
readonly GITHUB_API_URL="https://api.github.com/repos/Antoine-Flo/kubelocal/releases/latest"

# Get latest release version
get_latest_version() {
    local api_response
    
    api_response=$(curl -s "$GITHUB_API_URL") || exit 1
    local version
    version=$(echo "$api_response" | grep '"tag_name":' | cut -d'"' -f4)
    echo "$version"
}

# Main
version=$(get_latest_version)
echo "$version"
